base/urls.py
from django.urls import path
from django.views.generic import RedirectView, TemplateView

from base.views import BabyLoginView

urlpatterns = [
    path("", TemplateView.as_view(template_name="base/index.html"), name="index"),
    path("login/", BabyLoginView.as_view(), name="login"),
    path(
        "projects/",
        TemplateView.as_view(template_name="base/projects.html"),
        name="projects",
    ),
    path(
        "contact/",
        TemplateView.as_view(template_name="base/contact.html"),
        name="contact",
    ),
    path(
        "other/",
        TemplateView.as_view(template_name="base/other.html"),
        name="other",
    ),
    path(
        "talks/",
        TemplateView.as_view(template_name="base/talks.html"),
        name="talks",
    ),
    path("about/", RedirectView.as_view(url="/"), name="about"),
]

blog/urls.py
from django.urls import path

from blog.views import (
    BlogIndex,
    BlogPost,
    CategoryIndex,
    CommentView,
    MonthArchive,
    YearArchive,
)

app_name = "blog"
urlpatterns = [
    path("post/", BlogIndex.as_view(), name="index"),
    path("comment/", CommentView.as_view(), name="comment"),
    path("categories/<str:category>/", CategoryIndex.as_view(), name="category"),
    path("<int:year>/", YearArchive.as_view(), name="archive-year"),
    path("<int:year>/<int:month>/", MonthArchive.as_view(), name="archive-month"),
    path("<int:year>/<int:month>/<slug:slug>/", BlogPost.as_view(), name="detail"),
]

pdpv3/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from pdpv3.feed import LatestPostsFeed
from pdpv3.sitemaps import sitemaps

handler404 = "base.views.page_not_found"
handler500 = "base.views.internal_server_error"

urlpatterns = [
    path("", include("base.urls")),
    path("", include("blog.urls")),
    path("photos", include("photos.urls")),
    path("admin/", admin.site.urls),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("feed/", LatestPostsFeed()),
]

blog/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Post(models.Model):
    slug = models.SlugField(primary_key=True, db_index=True, max_length=100)
    title = models.CharField(max_length=200)
    date = models.DateTimeField(db_index=True)
    categories = ArrayField(models.CharField(max_length=50), blank=True)
    content = models.TextField(blank=True, default="")
    image = models.URLField(blank=True, default="")

    class Meta:
        ordering = ["-date"]

    def get_absolute_url(self):
        return reverse(
            "blog:detail",
            kwargs={
                "year": self.date.strftime("%Y"),
                "month": self.date.strftime("%m"),
                "slug": self.slug,
            },
        )

    @property
    def excerpt(self) -> str:
        splitter = "<!--more-->"
        if splitter in self.content:
            return self.content.split("<!--more-->")[0]
        else:
            if len(self.content) < 500:
                return self.content
            else:
                return self.content.split("\n")[0]

    def __str__(self):
        return self.slug


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now, blank=True)
    commenter = models.CharField(max_length=200, blank=True, default="")
    content = models.TextField()

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return f"{self.commenter} on {self.post}"

blog/views.py
from django import forms
from django.shortcuts import render
from django.views.generic import View
from django.views.generic.dates import (
    ArchiveIndexView,
    MonthArchiveView,
    YearArchiveView,
)
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from blog.models import Comment, Post


class BlogIndex(ArchiveIndexView):
    model = Post
    date_field = "date"
    paginate_by = 10
    template_name = "blog/list.html"


class YearArchive(YearArchiveView):
    model = Post
    date_field = "date"
    paginate_by = 20
    make_object_list = True
    template_name = "blog/list_short.html"


class MonthArchive(MonthArchiveView):
    model = Post
    date_field = "date"
    month_format = "%m"
    paginate_by = 20
    make_object_list = True
    template_name = "blog/list_short.html"


class CommentForm(forms.Form):
    commenter = forms.CharField(required=False, label="Name (optional)")
    content = forms.CharField(label="Comment", widget=forms.Textarea(attrs={"rows": 5}))
    post = forms.CharField(widget=forms.HiddenInput)
    # honeypot email field
    comment_email = forms.EmailField(required=False, label="Email (required)")
    # Math challenge
    challenge = forms.IntegerField(label="What is four plus two?")

    def clean_comment_email(self):
        email = self.cleaned_data["comment_email"]
        if email:
            raise forms.ValidationError("This is a honeypot")
        return email

    def clean_challenge(self):
        answer = self.cleaned_data["challenge"]
        if answer != 6:
            raise forms.ValidationError("This is a bot")
        return answer


class BlogPost(DetailView):
    model = Post
    template_name = "blog/post.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        comment_form = CommentForm(initial={"post": self.get_object().pk})
        context["comment_form"] = comment_form
        return context


class CommentView(View):
    def post(self, request):
        form = CommentForm(request.POST)
        if form.is_valid():
            post = Post.objects.get(pk=form.cleaned_data["post"])
            comment = Comment.objects.create(
                post=post,
                commenter=form.cleaned_data["commenter"],
                content=form.cleaned_data["content"],
            )
        else:
            # Make it look like a comment was posted but don't save it.
            comment = Comment(
                post=Post.objects.get(pk=request.POST["post"]),
                commenter=request.POST["commenter"],
                content=request.POST["content"],
            )
        return render(request, "blog/_comment.html", {"comment": comment})


class CategoryIndex(ListView):
    model = Post
    paginate_by = 20
    template_name = "blog/list_short.html"

    def get_queryset(self):
        category = self.kwargs["category"]
        return super().get_queryset().filter(categories__contains=[category])

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["category"] = self.kwargs["category"]
        return context

blog/templates/blog/_comment.html
<article class="comment" id="comment-{{ comment.id }}">
    <header>
        {% if comment.commenter %}
            {{ comment.commenter }}
        {% else %}
            anonymous
        {% endif %}
        {% if comment.parent %}
            <em>
                &nbsp;in response to
                <a href="#comment-{{comment.parent.id}}">{{ comment.parent.commenter }}</a>
            </em>
        {% endif %}
        <time datetime="{{comment.date|date:'c'}}">{{ comment.date }}</time>
    </header>
    {{ comment.content }}
</article>

blog/templates/blog/_micro.html
{% load blog_extras %}
<blockquote class="micro">
    {{ post.title|convert_markdown }}
    <footer>
        <cite>{{ post.date|date:"l N j, Y f a"}}</cite>
    </footer>
</blockquote>

blog/templates/blog/_pagination.html
<div class="pagination">
{% if page_obj.paginator.num_pages > 1 %}
    {% if page_obj.has_previous %}
        <div><a href="?page={{ page_obj.previous_page_number }}"><<</a></div>
    {% endif %}
        <progress value="{{ page_obj.number }}" max="{{ page_obj.paginator.num_pages }}">
        </progress>
    {% if page_obj.has_next %}
        <div><a href="?page={{ page_obj.next_page_number }}">>></a></div>
    {% endif %}
{% endif %}
</div>

blog/templates/blog/_title.html
<hgroup>
    <h3>
        <a class="u-url" href="{{ post.get_absolute_url }}">
            <span class="p-name">{{ post.title }}</span>
        </a>
    </h3>
    <p>
        🖊️
        <a rel="author" class="p-author h-card title-link" href="https://www.pedaldrivenprogramming.com">Austin Riba</a>
        ⌚
        <time class="dt-published" datetime="{{ post.date|date:'c' }}">
            {{ post.date|date:"j" }}
            <a class="title-link" href="{% url 'blog:archive-month' post.date|date:'Y' post.date|date:'m' %}">
                {{ post.date|date:"M"}}
            </a>
            <a class="title-link" href="{% url 'blog:archive-year' post.date|date:'Y' %}">
                {{ post.date|date:"Y"}}
            </a>
        </time>
        🔖
        <span class="p-category">
        {% for cat in post.categories %}
            <a class="title-link" href="{% url 'blog:category' cat %}">{{ cat }}</a>
        {% endfor %}
        </span>
        💬
        <a class="title-link" href="{{ post.get_absolute_url }}#comments">
            {{ post.comment_set.count }}
        </a>
    </p>
</hgroup>

blog/templates/blog/list.html
{% extends 'base/base.html' %}
{% load blog_extras %}
{% block content %}
{% for post in page_obj %}
    {% if not post.content %}
        {% include 'blog/_micro.html' with post=post %}
    {% else %}
        {% include 'blog/_title.html' with post=post %}
        {{ post.excerpt|convert_markdown }}
    {% endif %}
{% endfor %}
{% include 'blog/_pagination.html' with page_obj=page_obj %}
{% endblock %}

blog/templates/blog/list_short.html
{% extends 'base/base.html' %}
{% block content %}
<h2>
    {% if year %}
        {{ year|date:"Y"}}
    {% elif month %}
        {{ month|date:"F Y" }}
    {% elif category %}
        {{ category }}
    {% endif %}
</h2>
{% for post in page_obj %}
    {% include 'blog/_title.html' with post=post %}
{% empty %}
<p>No posts.</p>
{% endfor %}
{% include 'blog/_pagination.html' with page_obj=page_obj %}
{% endblock %}

blog/templates/blog/post.html
{% extends 'base/base.html' %}
{% load blog_extras %}
{% block title %}{{ object.title }}{% endblock %}
{% block description %}{{ object.excerpt|linebreaks|striptags }}{% endblock %}
{% block meta_image %}{% if post.image %}{{ post.image }}{% else %}{{block.super}}{% endif %}{% endblock %}
{% block content %}
<div class="h-entry">
{% include 'blog/_title.html' with post=object %}
<div class="e-content">{{ object.content|convert_markdown}}</div>
</div>
{% if object.comment_set.count > 0 %}
<hr/>
{% endif %}
<form method="POST"
        id="comments"
        hx-post="{% url 'blog:comment' %}"
        hx-target="#comment-list"
        hx-swap="afterbegin"
        hx-on::after-request="this.reset()"
>
    {% csrf_token %}
    {{ comment_form }}
    <input type="submit" value="Add Comment">
</form>

<div id="comment-list">
{% for comment in object.comment_set.all %}
    {% include 'blog/_comment.html' with comment=comment %}
{% endfor %}
</div>
{% endblock %}