base/urls.py
from django.urls import path
from django.views.generic import RedirectView, TemplateView

from base.views import BabyLoginView

urlpatterns = [
    path("", TemplateView.as_view(template_name="base/index.html"), name="index"),
    path("login/", BabyLoginView.as_view(), name="login"),
    path(
        "projects/",
        TemplateView.as_view(template_name="base/projects.html"),
        name="projects",
    ),
    path(
        "contact/",
        TemplateView.as_view(template_name="base/contact.html"),
        name="contact",
    ),
    path(
        "other/",
        TemplateView.as_view(template_name="base/other.html"),
        name="other",
    ),
    path(
        "talks/",
        TemplateView.as_view(template_name="base/talks.html"),
        name="talks",
    ),
    path("about/", RedirectView.as_view(url="/"), name="about"),
]

pdpv3/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from pdpv3.feed import LatestPostsFeed
from pdpv3.sitemaps import sitemaps

handler404 = "base.views.page_not_found"
handler500 = "base.views.internal_server_error"

urlpatterns = [
    path("", include("base.urls")),
    path("", include("blog.urls")),
    path("photos", include("photos.urls")),
    path("admin/", admin.site.urls),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("feed/", LatestPostsFeed()),
]

photos/urls.py
from django.urls import path

from photos.views import PhotoList

app_name = "photos"
urlpatterns = [
    path("", PhotoList.as_view(), name="index"),
]

photos/models.py
import secrets
from io import BytesIO

from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from PIL import Image, ImageOps


def image_upload_salt(instance, filename):
    return f"images/{instance.image_salt}-{filename}"


def thumb_upload_salt(instance, filename):
    return f"images/thumb/{instance.image_salt}-{filename}"


class PdpImage(models.Model):
    image = models.ImageField(upload_to=image_upload_salt)
    thumb = models.ImageField(upload_to=thumb_upload_salt, blank=True, null=True)
    description = models.CharField(max_length=200, blank=True, default="")
    private = models.BooleanField(blank=True, default=True)
    hidden = models.BooleanField(blank=True, default=False)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-date"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.image_salt = secrets.token_urlsafe(8)

    def __str__(self):
        return self.image.name

    def create_thumbnail(self):
        if not self.image:
            return

        image = Image.open(self.image)
        ImageOps.exif_transpose(image, in_place=True)
        image.thumbnail((800, 800))
        image_file = BytesIO()
        image.save(image_file, image.format)
        self.thumb.save(
            self.image.name,
            InMemoryUploadedFile(
                image_file,
                None,
                None,
                f"image/{image.format}",
                image_file.tell(),
                None,
            ),
            save=False,
        )

    def save(self, *args, **kwargs):
        self.create_thumbnail()
        return super().save(*args, **kwargs)

photos/views.py
from django.views.generic.list import ListView

from photos.models import PdpImage


class PhotoList(ListView):
    model = PdpImage
    paginate_by = 3

    def get_queryset(self):
        qs = super().get_queryset().exclude(hidden=True)
        if not self.request.user.is_authenticated:
            qs = qs.exclude(private=True)
        return qs

    def get_template_names(self, *args, **kwargs):
        if self.request.headers.get("HX-Request"):
            return ["photos/gallery_row.html"]
        else:
            return ["photos/gallery.html"]

photos/templates/photos/gallery.html
{% extends 'base/base.html' %}
{% block content %}
<hgroup>
    <h2>Gallery</h2>
    {% if not request.user.is_authenticated %}
    <p><a href="{% url 'login' %}">Show me baby 👶</a></p>
    {% endif %}
</hgroup>

<div class="gallery">
{% include "photos/gallery_row.html" with object_list=object_list page_obj=page_obj %}
</div>
<a onclick="history.back()" class="lightbox" id="lightbox">
    <span id="lightbox-bg"></span>
</a>
{% endblock %}
{% block extra_javascript %}
<script type="text/javascript">
    function setLightbox(url){
        document.getElementById("lightbox-bg").style.backgroundImage = `url(${url})`;
    }
</script>
{% endblock %}

photos/templates/photos/gallery_row.html
<div class="grid gallery-row">
    {% for photo in object_list %}
        {% if forloop.last and page_obj.has_next %}
            <div hx-get="{% url 'photos:index' %}?page={{ page_obj.number|add:'1' }}"
                hx-trigger="revealed"
                hx-swap="afterend"
                hx-target="closest .grid">
        {% else %}
            <div>
        {% endif %}
        <a href="#lightbox" onclick="setLightbox('{{ photo.image.url }}')">
            <figure>
                <img title="{{ photo.description }}" alt="{{ photo.description }}" src="{{ photo.thumb.url }}">
                <figcaption>{{ photo.description }} <br/> {{ photo.date }}</figcaption>
            </figure>
        </a>
    </div>
    {% endfor %}
</div>