base/urls.py
from django.urls import path
from django.views.generic import RedirectView, TemplateView

from base.views import BabyLoginView

urlpatterns = [
    path("", TemplateView.as_view(template_name="base/index.html"), name="index"),
    path("login/", BabyLoginView.as_view(), name="login"),
    path(
        "projects/",
        TemplateView.as_view(template_name="base/projects.html"),
        name="projects",
    ),
    path(
        "contact/",
        TemplateView.as_view(template_name="base/contact.html"),
        name="contact",
    ),
    path(
        "other/",
        TemplateView.as_view(template_name="base/other.html"),
        name="other",
    ),
    path(
        "talks/",
        TemplateView.as_view(template_name="base/talks.html"),
        name="talks",
    ),
    path("about/", RedirectView.as_view(url="/"), name="about"),
]

blog/urls.py
from django.urls import path

from blog.views import (
    BlogIndex,
    BlogPost,
    CategoryIndex,
    CommentView,
    MonthArchive,
    YearArchive,
)

app_name = "blog"
urlpatterns = [
    path("post/", BlogIndex.as_view(), name="index"),
    path("comment/", CommentView.as_view(), name="comment"),
    path("categories/<str:category>/", CategoryIndex.as_view(), name="category"),
    path("<int:year>/", YearArchive.as_view(), name="archive-year"),
    path("<int:year>/<int:month>/", MonthArchive.as_view(), name="archive-month"),
    path("<int:year>/<int:month>/<slug:slug>/", BlogPost.as_view(), name="detail"),
]

pdpv3/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from pdpv3.feed import LatestPostsFeed
from pdpv3.sitemaps import sitemaps

handler404 = "base.views.page_not_found"
handler500 = "base.views.internal_server_error"

urlpatterns = [
    path("", include("base.urls")),
    path("", include("blog.urls")),
    path("photos", include("photos.urls")),
    path("admin/", admin.site.urls),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("feed/", LatestPostsFeed()),
]

photos/urls.py
from django.urls import path

from photos.views import PhotoList

app_name = "photos"
urlpatterns = [
    path("", PhotoList.as_view(), name="index"),
]

base/models.py
# Create your models here.

base/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import render
from django.urls import reverse_lazy


def page_not_found(request, *args, **kwargs):
    return render(request, "base/404.html", status=404)


def internal_server_error(request, *args, **kwargs):
    return render(request, "base/500.html", status=500)


class BabyLoginView(LoginView):
    template_name = "base/login.html"
    next_page = reverse_lazy("photos:index")

    def get_initial(self):
        initial = super().get_initial()
        initial["username"] = "babyuser"
        return initial

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="author" content="Austin Riba">
      <meta name="description"
        content="{% block description %}A blog about technology and bikes by Austin Riba
        {% endblock %}">
      <meta property="og:image"
        content="{% block meta_image %}{% static 'base/img/logo.png' %}{% endblock %}">
      <title>
        {% block title %}Pedal Driven Programming{% endblock %}
      </title>
      {% block css %}
      <link rel="shortcut icon" type="image/png" href="{% static 'base/img/logo.png' %}">
      <link rel="shortcut icon" type="image/ico" href="{% static 'base/img/favicon.ico' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'pico/css/pico.lime.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'base/css/main.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'pygments/github.css' %}" media="(prefers-color-scheme: light)">
      <link rel="stylesheet" type="text/css" href="{% static 'pygments/native.css' %}" media="(prefers-color-scheme: dark)">
      {% endblock %}
      {% block extra_css %}{% endblock %}
  </head>
  <body>
    <script>0</script>
    <main class="container">
      <div class="grid-container">
        <aside class="main-nav">
          <nav>
            <ul>
              <li class="logo"><a href="{% url 'index' %}">
                {% include 'base/gears.svg' %}
              </a></li>
              <li><a href="{% url 'blog:index' %}">Blog</a></li>
              <li><a href="{% url 'photos:index' %}">Photos</a></li>
              <li><a href="{% url 'projects' %}">Projects</a></li>
              <li><a href="{% url 'talks' %}">Talks</a></li>
            </ul>
          </nav>
        </aside>
        <div class="content">
        {% block content %}
        {% endblock %}
        </div>
      </div>
    </main>
    <footer class="main-footer">
      <nav class="h-card">
        <ul>
          <li>
            <img alt="me" class="u-photo" src="{% static 'base/img/headshot.jpg' %}" width="50" height="50">
          </li>
          <li>
            <a class="p-name u-url" href="https://www.pedaldrivenprogramming.com">Austin Riba</a>
          </li>
          <li>
            <a href="https://github.com/Fingel" rel="me">Github</a>
          </li>
          <li>
            <a rel="me" href="https://indieweb.social/@Fingel">Mastodon</a>
          </li>
          <li>
            <a class="u-email" href="mailto:austin@m51.io" rel="me">austin@m51.io</a>
          </li>
          <li id="favorite-quote">
            <em>It doesn't get easier, you just get faster.</em>
          </li>
        </ul>
      </nav>
    </footer>
    {% block javascript %}
    <script defer src="{% static 'htmx/htmx.min.js' %}"></script>
    <script async src="{% static 'base/js/gears.js' %}"></script>
    {% endblock %}
    {% block extra_javascript %}{% endblock %}
  </body>
</html>

base/templates/base/contact.html
{% extends 'base/base.html' %}
{% block content %}
<p>Drop me a line at <a href="mailto:austin@m51.io">austin@m51.io</a></p>
{% endblock %}

base/templates/base/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<h1>Hi, I'm Austin Riba.</h1>
<p>
  I've been writing code for almost as long as I've been riding a bike. Over this time I've taken on the role of a generalist with experience in full stack development,
  devops and product management.
</p>
<p>
    I installed Linux on to my home computer in 6th grade and began web
    development shortly thereafter.
    I was excited by the possibility of being able to build something and
    share it with the world. I still get excited about that to this day.
</p>
<p>
    <a title="Pojects" href="{% url 'projects' %}">Projects</a>
    <a title="Experience" href="#experience">Experience</a>
    <a title="Github" href="https://github.com/Fingel">
      Github
    </a>
</p>
<img class="img-fluid" decoding="async" src="{% static 'base/img/biking.webp' %}" height="800">
<h2>Software Development</h2>
<p>
I'm happy to jump into existing projects and I excel at starting products from scratch. Taking an idea and turning it into a tangible
product is one of my favorite aspects of development. I can work with you through the process of requirement gathering, architecture, development, deployment and iteration.
</p>
<p>
  I may be available for software consultancy.
  <a href="mailto:austin@pedaldrivenprogramming.com">Contact me</a> if you are interested in working together.
</p>
<h2>Skills</h2>
<p>
  The technologies I work with the most, ordered from most to least familiarity:
</p>
<p>
  <strong>Languages:</strong> Python, Javascript, Java, shell, Go. <br>
  <strong>Backend:</strong> Django (DRF), Flask, FastAPI, Ruby on Rails. <br>
  <strong>Fontend:</strong> Vue.js, QT, jQuery, Angular. <br>
  <strong>Devops:</strong> Docker, AWS, Heroku. <br>
  <strong>Project Management:</strong> Trello, Pivotal, Atlassian.<br>
  <strong>Other: </strong> Linux, PostGIS, Ionic.
</p>
<p>
  I also have experience with software and tools specific to Astronomy including AstroPy, JS9, Astrometry.net, .fits files, etc.
</p>
<div class="page-break"></div>
<a name="experience"><h2>Experience</h2></a>
<table class="table">
  <tbody>
    <tr>
      <td>SRAM
      </td><td></td>
      <td>July 2022 - Present</td>
    </tr>
    <tr>
      <td colspan="3">
        <ul>
          <li>Making cool bike stuff! 🚲 🚲 🚲</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>Freelance Developer
      </td><td></td>
      <td>January 2020 - July 2022</td>
    </tr>
    <tr>
      <td colspan="3">
        <ul>
          <li>A few stealth projects still under development 😉</li>
        </ul>
        <ul>
          <li>Developed the <a href="https://www.goforwardlateral.com">Forward Lateral</a> lateral inspection software. Took the project
            from mockups, to a MVP, to full production deployment in less than 5 months. Read more in the
            <a href="https://www.independent.com/2020/02/14/forward-lateral-is-the-perfect-public-private-partnership-for-sewer-inspections/">Santa Barbara Independent</a>.
          </li>
          <li>
            Helped develop the <a href="http://treasuremap.space/">TreasureMap</a>, a web app designed to help astronomers with electromagnetic followup of gravitational-wave (GW) events.
          </li>
          <li>Merged my side project <a href="https://www.trail.care" title="Trail Care">Trail Care</a> with
            <a href="https://www.luvtrails.com" title="luvtrails">LuvTrails</a> to enhance both platforms and bring more business opportunity
            to the project.
          </li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>Las Cumbres Observatory</td>
      <td>Senior Software Engineer</td>
      <td>August 2015-January 2020</td>
    </tr>
    <tr>
      <td colspan="3">
        <ul>
          <li>
            Principal developer of the <a href="https://github.com/TomToolkit">TOM Toolkit project</a>, an open source
            framework built on Django for managing Astronomical observing programs.
          </li>
          <li>
            Built the <a href="https://archive.lco.global">LCO Archive</a>, a data warehouse and pipeline for 60+ TB
            of data on Amazon with a fully programmatic API.
          </li>
          <li>
            Designed and developed the <a href="https://observe.lco.global">Valhalla Observation Portal</a>: the main user
            facing interface for Astronomers into the observatory as well as the network's request database.
          </li>
          <li>
            Mentored and advised junior developers in an array of development projects.
          </li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>New Context Services</td>
      <td>Senior Software Engineer</td>
      <td>April 2015-August 2015</td>
    </tr>
    <tr>
      <td colspan="3">
        <ul>
          <li>
            Worked with a fully remote team on a legacy web project. Added extra functionality in the form of highly interactive
            and responsive pages using a modern JS framework with no negative impact to the legacy code.
          </li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>Silent Circle LCC</td>
      <td>Senior Software Engineer</td>
      <td>November 2013-April 2015</td>
    </tr>
    <tr>
      <td colspan="3">
        <ul>
          <li>
            Using a Django/ Python stack built out the business back end for the company’s application suite.
            Application was designed to handle user subscription, payment and authentication.
          </li>
          <li>
            Designed and built a business management dashboard for the largest clients designed to handle
            operations on hundreds of thousands of users.
          </li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>Locus Energy</td>
      <td>Software Engineer</td>
      <td>April 2011-October 2011</td>
    </tr>
    <tr>
      <td colspan="3">
        <ul>
          <li>
            Completed a contract to move the company's infrastructure from traditional hosting to AWS.
            Required migrating tens of Linux and Windows servers, a VPN and a clustered database on to
            Amazon's largest instance types (at the time).
          </li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>CSRware Inc</td>
      <td>Software Engineer</td>
      <td>April 2010-November 2013</td>
    </tr>
    <tr>
      <td colspan="3">
        <ul>
          <li>
            Using Spring and Java developed a SASS application for businesses that tracked their ecological impact
            by analyzing consumed utility bills and other raw data and computed emissions, waste, heat, etc.
          </li>
        </ul>
      </td>
    </tr>
  </tbody>
</table>
<h2>Education</h2>
<p><strong>2008-2011</strong> Southern Oregon University, B.S. Computer Science</p>
<h2>Pedal Driven?</h2>
<p>If you meet me in person, chances are I'll be wearing a pair of bike shoes with my laptop on my back. Not only is cycling one of my biggest hobbies, I believe in the bike's enormous potential to transform our lives through positive impacts on the environment, economics, social interaction, city planning and personal health. I <a href="/categories/cycling">write about it</a> from time to time.
    </p>
{% endblock %}

base/templates/base/login.html
{% extends 'base/base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.username.as_hidden }}
    <div class="fieldwrapper">
        {{ form.password.as_field_group }}
    </div>
    <input type="submit" value="Show me the baby pictures!">
</form>
{% endblock %}

base/templates/base/other.html
{% extends 'base/base.html' %}
{% block content %}
<p>Wip</p>
{% endblock %}

base/templates/base/projects.html
{% extends 'base/base.html' %}
{% block extra_css %}
 <link rel="stylesheet" type='text/css' href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />
{% endblock %}
{% block title %}Projects{% endblock %}
{% block content %}
<h3>Cycling</h3>
<ul>
  <li>
    <a href="https://trail.care">Trail Care</a>:
    Trail Care is a Strava integration/service that facilitates fast and simple micro donations
    from trail users to trail advocacy groups. It has raised thousands of dollars
    for various trail organizations around the US. It works by checking the GPS tracks of
    user's activities against a geospatial database of known trail organizations, and leveraging
    Stripe to make transactions.<br/>
    <i class="icon devicon-python-plain"></i>
    <i class="icon devicon-django-plain"></i>
    <i class="icon devicon-postgresql-plain"></i>
  </li>
  <li>
    <a href="http://granitemaps.com">GraniteMaps</a>:
    a collection of trail map apps for both
    Android and iOS. The maps work 100% offline, are GPS enabled,
    provide detailed trail descriptions and helpful information
    on local wildlife and emergency contacts. Featured in the <a href="http://www.santacruzsentinel.com/sports/20141208/santa-cruzan-creates-local-trail-map-app">Santa Cruz Sentinel</a> and <a href="http://hilltromper.com/article/wilder-ranch-map-granitemaps">Hilltromper</a>.<br/>
    <i class="icon devicon-javascript-plain"></i>
    <i class="icon devicon-angularjs-plain"></i>
    <i class="icon devicon-apple-plain"></i>
    <i class="icon devicon-android-plain"></i>
  </li>
</ul>
<h3>Development</h3>
<ul>
  <li>
    <a href="https://github.com/LCOGT/django-vitals">Django Vitals:</a> django-vitals is a
    Django app that provides health check endpoints for vital services. Extra checks are
    easy to write or extend.<br/>
    <a href="https://github.com/LCOGT/django-vitals">Source Code</a><br/>
    <i class="icon devicon-python-plain"></i>
    <i class="icon devicon-django-plain"></i>
  </li>
</ul>
<h3>Astronomy</h3>
<ul>
  <li>
    <a href="http://astrochallenge.com">Astrochallenge</a>: AstroChallenge is a
    online catalog, observation list, and social network for amateur astronomers.<br/>
    <i class="icon devicon-python-plain"></i>
    <i class="icon devicon-django-plain"></i>
    <i class="icon devicon-postgresql-plain"></i>
  </li>
</ul>
<h3>Miscellaneous</h3>
<ul>
  <li>
      <a href="/2018/09/tuimoji-terminal-emoji-chooser/">Tuimoji</a>:
      A terminal based emoji chooser.<br/>
      <i class="icon devicon-python-plain"></i>
  </li>
  <li>
    <a href="https://play.google.com/store/apps/details?id=com.ionicframework.k9cupid">K9Cupid</a>:
    A tinder clone for dogs. Made as a birthday gift for a special someone who really loves dogs.<br/>
    <i class="icon devicon-javascript-plain"></i>
    <i class="icon devicon-angularjs-plain"></i>
    <i class="icon devicon-android-plain"></i>
  </li>
  <li>
    <a href="https://participuppy.com/">Participuppy</a>: A classroom app for keeping tack of student
    participation.<br/>
    <i class="icon devicon-python-plain"></i>
    <i class="icon devicon-django-plain"></i>
    <i class="icon devicon-postgresql-plain"></i>
    <i class="icon devicon-javscript-plain"></i>
    <i class="icon devicon-vuejs-plain"></i>
  </li>
</ul>
{% endblock %}

base/templates/base/talks.html
{% extends 'base/base.html' %}
{% block content %}
<h3>🎬 TOM Toolkit Technical Overview</h3>
<p>The TOM Toolkit is a framework built on Django for creating astronomical
    management platforms.
</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/LEl7jkPmEyY?si=zPrzxma_S3rjanaM&amp;start=420" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
<h3>🎬 Building an Instagram Clone using Django</h3>
<p>A demonstration detailing how to create a file sharing app very quickly
    using Django.
</p>
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/7xahfqVN5ig" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<h3>🎧 Rising From the Ashes - Athletes Unfiltered Strava Podcast</h3>
<p>I told the story of the Santa Barbara wildfires and how
    they inspired me to create <a href="https://trail.care">Trail Care</a>.
<p>
    <a href="https://podcasts.apple.com/us/podcast/rising-from-the-ashes/id1447430288?i=1000428271279">Listen on Apple Podcasts</a>
</p>
<h3>🎧 The MORE Trail Report - Trail.Care</h3>
<p>I spoke with the Mid-Atlantic Off-Road Enthusiasts trail report about my project
    <a href="https://trail.care">Trail Care</a> and how it can help trail organizations
    and advocacy groups.
</p>
<p><a href="https://more-mtb.org/blogs/news/the-more-trail-report-episode-5-trail-care">
    Listen here.
</a>
</p>
<h3>📜 Las Cumbres Observatory's end-to-end Operations Workflow</h3>
<p>Read it on <a href="https://www.spiedigitallibrary.org/conference-proceedings-of-spie/11449/1144907/Las-Cumbres-Observatorys-end-to-end-operations-workflow/10.1117/12.2561964.short">
    SPIE
</a>
</p>
{% endblock %}